# Base namespace for all generated files
namespace = "LoyaltyCandy"

# Will create a subfolder within this directory with all the files
output-directory = "./Clients"

# Will override default boundry node url (like for local development)
# Only useful for generating clients from a canister id
url = "http://localhost:8080"

# Will make generated files in a flat structure with no folders, for all clients
#no-folders = true

# Defines name folder and api client class name
# Get the definition from a live canister on the IC
# Canister to pull definition from
[[clients]]
name = "NNSRegistry"
type = "canister"
canister-id = "rwlgt-iiaaa-aaaaa-aaaaa-cai"

[[clients]]
name = "NNSGovernance"
type = "canister"
canister-id = "rrkah-fqaaa-aaaaa-aaaaq-cai"

[[clients]]
name = "NNSLedger"
type = "canister"
canister-id = "ryjl3-tyaaa-aaaaa-aaaba-cai"

[[clients]]
name = "NNSRoot"
type = "canister"
canister-id = "r7inp-6aaaa-aaaaa-aaabq-cai"

[[clients]]
name = "NNSCyclesMinting"
type = "canister"
canister-id = "rkp4c-7iaaa-aaaaa-aaaca-cai"

[[clients]]
name = "NNSGenesisToken"
type = "canister"
canister-id = "renrk-eyaaa-aaaaa-aaada-cai"

[[clients]]
name = "InternetIdentity"
type = "canister"
canister-id = "qhbym-qaaaa-aaaaa-aaafq-cai"

[[clients]]
name = "NNSDapp"
type = "canister"
canister-id = "qsgjb-riaaa-aaaaa-aaaga-cai"


# Get definition from a *.did file
#type = "file"
# Path to the *.did file to use
#file-path = "../MyService.did"


# Override base output directory, but this specifies the subfolder
#output-directory = "./Clients/MyS"

# Will make generated files in a flat structure with no folders, for this client
#no-folders = true

# Can specify multiple clients by creating another [[clients]]
#[[clients]]
#name = "MyClient2"
#type = "file"
#file-path = "../MyService2.did"
				