# Base namespace for all generated files
namespace = "LoyaltyCandy"

# Will create a subfolder within this directory with all the files
output-directory = "./Clients"

# Will override default boundry node url (like for local development)
# Only useful for generating clients from a canister id
url = "http://localhost:4943"

# Will make generated files in a flat structure with no folders, for all clients
#no-folders = true

# Defines name folder and api client class name
# Get the definition from a live canister on the IC
# Canister to pull definition from
[[clients]]
name = "HelloClient"
type = "canister"
canister-id = "bkyz2-fmaaa-aaaaa-qaaaq-cai"

[[clients]]
name = "ClimateWallet"
type = "canister"
canister-id = "br5f7-7uaaa-aaaaa-qaaca-cai"

# Get definition from a *.did file
#type = "file"
# Path to the *.did file to use
#file-path = "../MyService.did"


# Override base output directory, but this specifies the subfolder
#output-directory = "./Clients/MyS"

# Will make generated files in a flat structure with no folders, for this client
#no-folders = true

# Can specify multiple clients by creating another [[clients]]
#[[clients]]
#name = "MyClient2"
#type = "file"
#file-path = "../MyService2.did"
				